		<div class="logo"><a href="">AVELANGO - Качественнее! Быстрее! Дешевле! </a></div>
		<ul class="mainmenu">
			<li class="active"><a href="#" class="mainorders">Заказы</a></li>
			<li><a href="#" class="mainexecutor">Исполнители</a></li>
		</ul>
		<div class="add_adv"><a href="ajax/wizard-step1.html" title="добавить объявление" class="btn-blue" data-toggle="modal" data-target="#myModal">Дать обьявление</a></div>
		<ul class="userinfo">
			<li><a href="#message" class="message" title="У вас 99+ событий"><i>99</i></a></li>
			<li class="avatar"><img src="img/XJg3_ubOpJ0.jpg" alt="Тумба Юмбович" title="Тумба Юмбович" width="57" height="57" /></li>
			<li><a href="#usermenu" class="usermenu" title="Меню пользователя Тумба Юмбович">menu</a></li>
		</ul>
		<div id="dropmainmenu" class="dropmainmenu hide">
			<ul>
				<li><a href="#">личный кабинет</a></li>
				<li><a href="#">мои заказы</a></li>
				<li><a href="#">поддержка</a></li>
			</ul>
			<hr/>
			<ul>
				<li><a href="#">выход</a></li>
			</ul>
		</div>