<div class="side-world">
	<h3 class="world-advert">Международные объявления</h3>
	<div class="item-int advert">
		<div class="item-int-img-box"> <img src="img/img11.jpg" width="85" height="85" class="item-int-img" alt=""/><span class="item-status item-online"><i>online</i></span></div>
		<div class="about-box">
			<h4 class="item-title">Hedge fund slide presentation</h4>
		</div>
		<div class="info-box">
			<div class="price">&#36; 3 187</div>
			<div class="item-int-location">Texas state, USA</div>
		</div>
	</div>
	<div class="item-int advert">
		<div class="item-int-img-box"> <img src="img/img22.jpg" width="85" height="85" class="item-int-img" alt=""/> <span class="item-status item-offline"><i>offline</i></span></div>
		<div class="about-box">
			<h4 class="item-int-title">Научить медведя танцевать на одной ноге при этом пить настойку на клюкве и играть на балалайке</h4>
		</div>
		<div class="info-box">
			<div class="price">&#8381; 1 155</div>
			<div class="item-int-location">Кемеровская область, Российская Федерация</div>
		</div>
	</div>
	<div class="item-int advert">
		<div class="item-int-img-box"> <img src="img/img33.jpg" width="85" height="85" class="item-int-img" alt=""/> <span class="item-status item-online"><i>online</i></span></div>
		<div class="about-box">
			<h4 class="item-int-title">Потрібно роздрукувати 20 000 листівок та рознести їх по поштовим скринькам</h4>
		</div>
		<div class="info-box">
			<div class="price">&#8372; 221 554</div>
			<div class="item-int-location">Івано-Франківська область, Україна</div>
		</div>
	</div>
	<div class="item-int advert">
		<div class="item-int-img-box"> <img src="img/img44.jpg" width="85" height="85" class="item-int-img" alt=""/> <span class="item-status item-offline"><i>offline</i></span></div>
		<div class="about-box">
			<h4 class="item-int-title">Google Adword/Analytics and Social medial marketing optimization (Twitter, Linkedin, Facebook) </h4>
		</div>
		<div class="info-box">
			<div class="price">&#8364; 23 014</div>
			<div class="item-int-location">Freie Hansestadt Bremen, Deutschland</div>
		</div>
	</div>
	<div class="item-int advert">
		<div class="item-int-img-box"> <img src="img/img55.jpg" width="85" height="85" class="item-int-img" alt=""/> <span class="item-status item-offline"><i>offline</i></span></div>
		<div class="about-box">
			<h4 class="item-int-title">Design a simple membership site for clients to login and view information</h4>
		</div>
		<div class="info-box">
			<div class="price">&#163; 2 553</div>
			<div class="item-int-location">Yorkshire and the Humber, Great Britain</div>
		</div>
	</div>
</div>