<div class="side-world">
	<h3 class="world-person">Международные исполнители</h3>
	<div class="item-int person">
		<div class="item-int-img-box"> <img src="img/img33.jpg" width="85" height="85" class="item-int-img" alt=""/> </div>
		<div class="about-box">
			<h4 class="item-int-title">Степан Буряк</h4>
			<div class="item-int-product"><img src="i/icon/icon-car-gre.svg" width="20px"  alt="">Перевозки</div>
			<div class="item-int-location">Texas state, USA</div>
		</div>
		<div class="info-box">
			<div class="raiting"> <i class="staryellow"></i> <i class="staryellow"></i> <i class="staryellow"></i> <i class="staryellow"></i> <i class="stargrey"></i> </div>
			<div class="rait"> 415</div>
		</div>
	</div>
	<div class="item-int person">
		<div class="item-int-img-box"> <img src="img/img55.jpg" width="85" height="85" class="item-int-img" alt=""/> </div>
		<div class="about-box">
			<h4 class="item-int-title">Васелиса Нестерова</h4>
			<div class="item-int-product"><img src="i/icon/icon-car-gre.svg" width="20px"  alt="">Перевозки</div>
			<div class="item-int-location">Волгоградская область, Российская Федерация</div>
		</div>
		<div class="info-box">
			<div class="raiting"> <i class="staryellow"></i> <i class="staryellow"></i> <i class="staryellow"></i> <i class="stargrey"></i> <i class="stargrey"></i> </div>
			<div class="rait"> 210</div>
		</div>
	</div>
	<div class="item-int person">
		<div class="item-int-img-box"> <img src="img/img11.jpg" width="85" height="85" class="item-int-img" alt=""/> </div>
		<div class="about-box">
			<h4 class="item-int-title">Эдуард Пихни</h4>
			<div class="item-int-product"><img src="i/icon/icon-car-gre.svg" width="20px"  alt="">Перевозки</div>
			<div class="item-int-location">Івано-Франківська область, Україна</div>
		</div>
		<div class="info-box">
			<div class="raiting"> <i class="staryellow"></i> <i class="staryellow"></i> <i class="stargrey"></i> <i class="stargrey"></i> <i class="stargrey"></i> </div>
			<div class="rait"> 55</div>
		</div>
	</div>
	<div class="item-int person">
		<div class="item-int-img-box"> <img src="img/img22.jpg" width="85" height="85" class="item-int-img" alt=""/> </div>
		<div class="about-box">
			<h4 class="item-int-title">Михаил Масловский</h4>
			<div class="item-int-product"><img src="i/icon/icon-car-gre.svg" width="20px" alt="" /> Перевозки</div>
			<div class="item-int-location">Yorkshire and the Humber, Great Britain</div>
		</div>
		<div class="info-box">
			<div class="raiting"> <i class="staryellow"></i> <i class="staryellow"></i> <i class="staryellow"></i> <i class="staryellow"></i> <i class="staryellow"></i> </div>
			<div class="rait"> 518</div>
		</div>
	</div>
	<div class="item-int person">
		<div class="item-int-img-box"> <img src="img/img44.jpg" width="85" height="85" class="item-int-img" alt=""/> </div>
		<div class="about-box">
			<h4 class="item-int-title">Ванесса Мэй</h4>
			<div class="item-int-product"><img src="i/icon/icon-car-gre.svg" width="20px" alt="" />Перевозки</div>
			<div class="item-int-location">Freie Hansestadt Bremen, Deutschland</div>
		</div>
		<div class="info-box">
			<div class="raiting"> <i class="staryellow"></i> <i class="stargrey"></i> <i class="stargrey"></i> <i class="stargrey"></i> <i class="stargrey"></i> </div>
			<div class="rait"> 258</div>
		</div>
	</div>
</div>