<a id="filterclose" class="filterclose" href="#" title="Закрыть фильтр">Закрыть фильтр</a>
	<form action="#">
		<div class="filter">
			<div class="filterholder">
				<div><a href="#" class="btnbulet btnup">Вверх</a></div>
				<ul class="filterlist">
					<li>
						<input type="checkbox" id="inp1" name="inp1" >
						<label for="inp1"><img src="i/icon/icon-help-gre.svg" width="21px" alt="Помощь"> Помощь </label>
						<ul>
							<li>
								<input type="checkbox" id="inp2" name="inp2" >
								<label for="inp2">Забота о людях</label>
							</li>
							<li>
								<input type="checkbox" id="inp3" name="inp3" >
								<label for="inp3">Уход За Животными </label>
							</li>
							<li>
								<input type="checkbox" id="inp4" name="inp4" >
								<label for="inp4">Мелкие бытовые услуги</label>
							</li>
							<li>
								<input type="checkbox" id="inp5" name="inp5" >
								<label for="inp5">Сад, огород,</label>
							</li>
							<li>
								<input type="checkbox" id="inp6" name="inp6" >
								<label for="inp6">Ремонт элементов </label>
							</li>
							<li>
								<input type="checkbox" id="inp7" name="inp7" >
								<label for="inp7">Услуги Шеф-Повара</label>
							</li>
							<li>
								<input type="checkbox" id="inp8" name="inp8" >
								<label for="inp8">Очистка больших объемов</label>
							</li>
							<li>
								<input type="checkbox" id="inp9" name="inp9" >
								<label for="inp9">Борьба с вредителями</label>
							</li>
							<li>
								<input type="checkbox" id="inp0" name="inp0" >
								<label for="inp0">Все категори</label>
							</li>
						</ul>
					</li>
					<li>
						<input type="checkbox" id="pr1" name="pr1" >
						<label for="pr1"><img src="i/icon/icon-car-gre.svg" width="21px" alt="Перевозки">Перевозки</label>
					</li>
					<li>
						<input type="checkbox" id="rem1" name="rem1" >
						<label for="rem1"><img src="i/icon/icon-repair-gr.svg" width="21px" alt="">Ремонт</label>
					</li>
					<li>
						<input type="checkbox" id="pok1" name="pok1" >
						<label for="pok1"><img src="i/icon/icon-orders-gr.svg" width="21px" alt="">Покупки</label>
					</li>
					<li>
						<input type="checkbox" id="zdor1" name="zdor1" >
						<label for="zdor1"><img src="i/icon/icon-med-gre.svg" width="21px" alt="">Здоровье</label>
					</li>
					<li>
						<input type="checkbox" id="obr1" name="obr1" >
						<label for="obr1"><img src="i/icon/icon-tich-gre.svg" width="21px" alt="">Образование</label>
					</li>
					<li>
						<input type="checkbox" id="inf1" name="inf1" >
						<label for="inf1"><img src="i/icon/icon-info-gre.svg" width="21px" alt="">Информационные</label>
					</li>
					<li>
						<input type="checkbox" id="str1" name="str1" >
						<label for="str1"><img src="i/icon/icon-build-gre.svg" width="21px" alt="">Строительство</label>
					</li>
					<li>
						<input type="checkbox" id="spr1" name="spr1" >
						<label for="spr1"><img src="i/icon/icon-sport-gre.svg" width="21px" alt="">Спорт</label>
					</li>
					<li>
						<input type="checkbox" id="dr1" name="dr1" >
						<label for="dr1"><img src="i/icon/icon-more-gre.svg" width="21px" alt="">Другие</label>
					</li>
				</ul>
				<div><a href="#" class="btnbulet active btndown">Вниз</a></div>
			</div>
			<input class="findplace" type="text" placeholder="Выбор расположения">
			<div class="clearfix">
				<button class="resetfilter" type="reset" >Сброс</button>
				<div class="onlinebtn">
					<input type="checkbox" id="onn" name="onn">
					<label for="onn">Оnline</label>
				</div>
			</div>
			<button type="submit" class="apllybtn" >Фильтровать</button>
			<p class="allcat"><a href="#">Все категории</a></p>
		</div>
	</form>