<div class="comments">
	<div class="list-block">
		<div class="list-item ">
			<div class="img-box-holder">
				<div class="img-box"> <img src="img/img4.jpg" width="100" height="100" class="item-img" alt=""/> <span class="item-status item-online"><i>online</i></span> </div>
			</div>
			<div class="about-box-holder">
				<div class="about-box">
					<h4 class="item-title">Артем Сидоренко</h4>
					<p class="item-about">Для фирмы требуется создать мессенеджер для сотрудников, с картографией, и позиционированием.Дополнительный функционал будет оговорен при личном общении.Приложение должно быть удобное </p>
				</div>
			</div>
		</div>
		<div class="list-item comment">
			<div class="img-box-holder">
				<div class="img-box"> <img src="img/img2.jpg" width="100" height="100" class="item-img" alt=""/> <span class="item-status item-online"><i>online</i></span> </div>
			</div>
			<div class="about-box-holder">
				<div class="about-box">
					<h4 class="item-title">Анна Федюкова-Герасименко</h4>
					<p class="item-about">Я в отличии от других исполнителей быстрее всех отвожу посылки по скольку у меня есть ракета в которой скорость движения достигает скорости света она работает от генератора черной дыры Для фирмы требуется создать мессенеджер для сотрудников, с картографией, и позиционированием.Дополнительный функционал будет оговорен при личном общении.Приложение должно быть удобное </p>
				</div>
			</div>
		</div>
		<div class="list-item comment">
			<div class="img-box-holder">
				<div class="img-box"> <img src="img/img1.jpg" width="100" height="100" class="item-img" alt=""/> <span class="item-status item-online"><i>online</i></span> </div>
			</div>
			<div class="about-box-holder">
				<div class="about-box">
					<h4 class="item-title">Василиса Егоровна</h4>
					<p class="item-about">Для фирмы требуется создать мессенеджер для сотрудников, с картографией, и позиционированием.Дополнительный функционал будет оговорен при личном общении.Приложение должно быть удобное </p>
				</div>
			</div>
		</div>
	</div>
	<hr/>
	<div class="addcoment">
		<form action="#">
			<div>
				<textarea placeholder="сделайте клик для начала ввода комментария"></textarea>
				<button type="submit" class="btn-orange" >оставить комментарий</button>
			</div>
		</form>
	</div>
</div>